<?php

use Aura\Router\RouterContainer;
use EvanG\Modules\MailSystem\AdminAction;
use EvanG\Modules\MailSystem\RequestHandler;
use EvanG\Modules\MailSystem\Settings;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Module\FamilyTreeNewsModule;
use Fisharebest\Webtrees\Services\ModuleService;

/**
 * @var string $title
 * @var Settings $settings
 */

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<div id="reminder-admin-config">

    <h1><?= $title ?></h1>

    <div id="reminder-admin-config-content">

        <div id="first-steps">
            <h2 style="margin-top: 1em;"><?= I18N::translate('First steps') ?></h2>
            <p>
                <?= I18N::translate('This module requires a cron job to be set up and run every day.') ?>
                <br>
                <?= I18N::translate('Please add the following line to your cron file') ?>
            </p>
            <input type="text" class="form-control" id="reminder-admin-config-cron-input" readonly
                   value="0 8 * * * wget -O - -q &quot;<?= e(route(RequestHandler::class, ['action' => 'cron'])) ?>&quot;">
            <div class="form-text">
                <?= I18N::translate('You may need to add %1$s and %2$s depending on your configuration', "<code>--no-check-certificate</code>", "<code>--no-hsts</code>") ?>
            </div>
        </div>

        <div id="settings">
            <form action="<?= route(AdminAction::class) ?>" method="get" class="form-horizontal">
                <input type="hidden" name="route" value="<?= app(RouterContainer::class)->getMap()->getRoute(AdminAction::class)->path; ?>" />
                <div id="settings-general" class="settings-cat mt-5">
                    <h2 style="margin-top: 1em;"><?= I18N::translate('General settings') ?></h2>

                    <!-- EVANG_MAILSYSTEM_TREES -->
                    <div class="row mb-3">
                        <label class="col-sm-3" for="EVANG_MAILSYSTEM_TREES">
                            <?= I18N::translate('Trees') ?>
                        </label>

                        <div class="col-sm-9">
                            <?= view('components/select', ['class' => 'tom-select', 'id' => 'EVANG_MAILSYSTEM_TREES', 'name' => 'EVANG_MAILSYSTEM_TREES[]', 'options' => $settings->getAllTrees(), 'selected' => $settings->getTrees()]) ?>
                            <div class="form-text">
                                <?= I18N::translate("Trees to be considered (User restrictions take precedence over this setting)") ?>
                            </div>
                        </div>
                    </div>

                    <!-- EVANG_MAILSYSTEM_USERS -->
                    <div class="row mb-3">
                        <label class="col-sm-3" for="EVANG_MAILSYSTEM_USERS">
                            <?= I18N::translate('Users') ?>
                        </label>

                        <div class="col-sm-9">
                            <?= view('components/select', ['class' => 'tom-select', 'id' => 'EVANG_MAILSYSTEM_USERS', 'name' => 'EVANG_MAILSYSTEM_USERS[]', 'options' => $settings->getAllUsers(), 'selected' => $settings->getUsers()]) ?>
                            <div class="form-text">
                                <?= I18N::translate("Users to send the mail to") ?>
                            </div>
                        </div>
                    </div>

                    <!-- EVANG_MAILSYSTEM_DAYS -->
                    <div class="row mb-3">
                        <label for="EVANG_MAILSYSTEM_DAYS" class="col-sm-3 col-form-label">
                            <?= I18N::translate('Frequency') ?>
                        </label>
                        <div class="col-sm-9">
                            <input type="number" step="1" pattern="^\d*$" class="form-control" id="EVANG_MAILSYSTEM_DAYS" name="EVANG_MAILSYSTEM_DAYS"
                                   value="<?= $settings->getDays() ?>"
                                   placeholder="7" maxlength="3">
                            <div class="form-text">
                                <?= I18N::translate('Frequency of sending e-mails (in days)') ?>
                            </div>
                        </div>
                    </div>

                    <!-- EVANG_MAILSYSTEM_EMPTY -->
                    <fieldset class="row mb-3">
                        <legend class="col-form-label col-sm-3">
                            <?= I18N::translate('Show empty categories') ?>
                        </legend>
                        <div class="col-sm-9">
                            <?= view('components/radios-inline', ['name' => 'EVANG_MAILSYSTEM_EMPTY', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int)$settings->getEmpty()]) ?>
                            <div class="form-text">
                                <?= I18N::translate("If this option is enabled, a message will indicate that there is no data to display for the period.") ?><br/>
                                <?= I18N::translate("When this option is disabled, in case all categories of all trees are without data, no mail will be sent.") ?>
                            </div>
                        </div>
                    </fieldset>

                    <!-- EVANG_MAILSYSTEM_IMAGEDATA -->
                    <fieldset class="row mb-3">
                        <legend class="col-form-label col-sm-3">
                            <?= I18N::translate('Images') ?>
                        </legend>
                        <div class="col-sm-9">
                            <?= view('components/radios-inline', ['name' => 'EVANG_MAILSYSTEM_IMAGEDATA', 'options' => $settings->getAllImageDataType(), 'selected' => $settings->getImageDataType()]) ?>
                            <div class="form-text">
                                <?= I18N::translate("Data URLs only work on relatively recent email clients."); ?><br />
                                <?= I18N::translate("Direct URLs should offer broad compatibility, but are slightly less secure, as image of individuals become available without authentication (they are resized to 50x50 px, however).") ?>
                            </div>
                        </div>
                    </fieldset>

                    <!-- EVANG_MAILSYSTEM_IMAGEFORMAT -->
                    <fieldset class="row mb-3">
                        <legend class="col-form-label col-sm-3">
                            <?= I18N::translate('Image format') ?>
                        </legend>
                        <div class="col-sm-9">
                            <?= view('components/radios-inline', ['name' => 'EVANG_MAILSYSTEM_IMAGEFORMAT', 'options' => $settings->getAllImageFormat(), 'selected' => $settings->getImageFormat()]) ?>
                            <div class="form-text">
                                <?= I18N::translate("Use PNG for a better compatibility") ?>
                            </div>
                        </div>
                    </fieldset>
                </div>

                <div id="settings-news" class="settings-cat mt-5">
                    <h2 style="margin-top: 1em;"><?= I18N::translate('News settings') ?></h2>

                    <!-- EVANG_MAILSYSTEM_NEWS_ENABLED -->
                    <fieldset class="row mb-3">
                        <legend class="col-form-label col-sm-3">
                            <?= I18N::translate('Enabled') ?>
                        </legend>
                        <div class="col-sm-9">
                            <?= view('components/radios-inline', ['name' => 'EVANG_MAILSYSTEM_NEWS_ENABLED', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int)$settings->getNewsEnabled()]) ?>
                            <div class="form-text">
                                <?= I18N::translate("Displays family news and site announcements (requires activation of the dedicated module)") ?>
                                <?php
                                    $module_service = app(ModuleService::class);
                                    assert($module_service instanceof ModuleService);
                                    $newsModule = $module_service->findByInterface(FamilyTreeNewsModule::class, true)->first();
                                    if ($newsModule == null) : ?>
                                        <br /><?= I18N::translate("The %1\$s module could not be found", "<code>News</code>") ?>
                                    <?php elseif (!$newsModule->isEnabled()) : ?>
                                        <br /><strong><?= I18N::translate('The %1$s module is disabled, please enable it if you wish to use this feature.', "<code>{$newsModule->title()}</code>") ?></strong>
                                    <?php endif ?>
                            </div>
                        </div>
                    </fieldset>
                </div>

                <div id="settings-changelist" class="settings-cat mt-5">
                    <h2 style="margin-top: 1em;"><?= I18N::translate('Change-list settings') ?></h2>

                    <!-- EVANG_MAILSYSTEM_CHANGE_ENABLED -->
                    <fieldset class="row mb-3">
                        <legend class="col-form-label col-sm-3">
                            <?= I18N::translate('Enabled') ?>
                        </legend>
                        <div class="col-sm-9">
                            <?= view('components/radios-inline', ['name' => 'EVANG_MAILSYSTEM_CHANGE_ENABLED', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int)$settings->getChangelistEnabled()]) ?>
                            <div class="form-text">
                                <?= I18N::translate("List of changes made in the previous period") ?>
                            </div>
                        </div>
                    </fieldset>

                    <!-- EVANG_MAILSYSTEM_CHANGE_TAGS -->
                    <div class="row mb-3">
                        <label class="col-sm-3" for="EVANG_MAILSYSTEM_CHANGE_TAGS">
                            <?= I18N::translate('Tags') ?>
                        </label>

                        <div class="col-sm-9">
                            <?= view('components/select', ['class' => 'tom-select', 'id' => 'EVANG_MAILSYSTEM_CHANGE_TAGS', 'name' => 'EVANG_MAILSYSTEM_CHANGE_TAGS[]', 'options' => $settings->getAllChangelistTags(), 'selected' => $settings->getChangelistTags()]) ?>
                            <div class="form-text">
                                <?= I18N::translate("Types of changes to be considered") ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div id="settings-anniversaries" class="settings-cat mt-5">
                    <h2 style="margin-top: 1em;"><?= I18N::translate('Anniversaries settings') ?></h2>

                    <!-- EVANG_MAILSYSTEM_ANNIV_ENABLED -->
                    <fieldset class="row mb-3">
                        <legend class="col-form-label col-sm-3">
                            <?= I18N::translate('Enabled') ?>
                        </legend>
                        <div class="col-sm-9">
                            <?= view('components/radios-inline', ['name' => 'EVANG_MAILSYSTEM_ANNIV_ENABLED', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int)$settings->getAnniversariesEnabled()]) ?>
                            <div class="form-text">
                                <?= I18N::translate("List of upcoming anniversaries in the next period") ?>
                            </div>
                        </div>
                    </fieldset>

                    <!-- EVANG_MAILSYSTEM_ANNIV_TAGS -->
                    <div class="row mb-3">
                        <label class="col-sm-3" for="EVANG_MAILSYSTEM_ANNIV_TAGS">
                            <?= I18N::translate('Tags') ?>
                        </label>

                        <div class="col-sm-9">
                            <?= view('components/select', ['class' => 'tom-select', 'id' => 'EVANG_MAILSYSTEM_ANNIV_TAGS', 'name' => 'EVANG_MAILSYSTEM_ANNIV_TAGS[]', 'options' => $settings->getAllAnniversariesTags(), 'selected' => $settings->getAnniversariesTags()]) ?>
                            <div class="form-text">
                                <?= I18N::translate("Types of events to consider") ?>
                            </div>
                        </div>
                    </div>


                    <!-- EVANG_MAILSYSTEM_ANNIV_DECEASED -->
                    <fieldset class="row mb-3">
                        <legend class="col-form-label col-sm-3">
                            <?= I18N::translate('Deceased persons') ?>
                        </legend>
                        <div class="col-sm-9">
                            <?= view('components/radios-inline', ['name' => 'EVANG_MAILSYSTEM_ANNIV_DECEASED', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int)$settings->getAnniversariesDeceased()]) ?>
                            <div class="form-text">
                                <?= I18N::translate("Display the anniversaries of deceased persons") ?><br />
                                <?= I18N::translate("Required for death anniversaries") ?>
                            </div>
                        </div>
                    </fieldset>
                </div>

                <div id="settings-footer" class="settings-cat mt-5">
                    <h2 style="margin-top: 1em;"><?= I18N::translate('Footer settings') ?></h2>

                    <!-- EVANG_MAILSYSTEM_FOOTER_ENABLED -->
                    <fieldset class="row mb-3">
                        <legend class="col-form-label col-sm-3">
                            <?= I18N::translate('Enabled') ?>
                        </legend>
                        <div class="col-sm-9">
                            <?= view('components/radios-inline', ['name' => 'EVANG_MAILSYSTEM_FOOTER_ENABLED', 'options' => [I18N::translate('no'), I18N::translate('yes')], 'selected' => (int)$settings->getFooterEnabled()]) ?>
                            <div class="form-text">
                                <?= I18N::translate("Adds a footer to the email") ?>
                            </div>
                        </div>
                    </fieldset>

                    <!-- EVANG_MAILSYSTEM_FOOTER_MESSAGE -->
                    <div class="row mb-3">
                        <label for="EVANG_MAILSYSTEM_FOOTER_MESSAGE" class="col-sm-3 col-form-label">
                            <?= I18N::translate('Message') ?>
                        </label>
                        <div class="col-sm-9">
                            <textarea class="form-control" id="EVANG_MAILSYSTEM_FOOTER_MESSAGE" name="EVANG_MAILSYSTEM_FOOTER_MESSAGE"><?= $settings->getFooterMessage() ?></textarea>
                            <div class="form-text">
                                <?= I18N::translate('The message to write (you can use HTML)') ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row mb-3 mt-5">
                    <div class="offset-sm-3 col-sm-9">
                        <button type="submit" class="btn btn-primary">
                            <?= view('icons/save') ?>
                            <?= I18N::translate('save') ?>
                        </button>

                        <a href="<?= e(route(ControlPanel::class)) ?>" class="btn btn-secondary">
                            <?= view('icons/cancel') ?>
                            <?= I18N::translate('cancel') ?>
                        </a>
                    </div>
                </div>
            </form>
        </div>

        <div id="information">
            <h2 style="margin-top: 1em;"><?= I18N::translate('Information') ?></h2>
            <p>
                <?php
                $lastSend = $settings->getLastSend();
                $lastSendText = $lastSend == null ? I18N::translate('never') : $lastSend->format('Y-m-d');
                $nextSend = $settings->getThisSend();
                $recipientsCount = count($settings->getUsers());
                ?>
                <?= I18N::translate('Last mailing: %s', "<code>$lastSendText</code>") ?>
                <br/>
                <?= I18N::translate('Next mailing: %s', "<code>{$nextSend->format('Y-m-d')}</code>") ?>
                <br/>
                <?= I18N::translate('Number of recipients: %s', "<code>$recipientsCount</code>") ?>
            </p>
        </div>
    </div>

</div>
