<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;

use Fisharebest\Webtrees\Module\ModuleGlobalInterface;
use Fisharebest\Webtrees\Module\ModuleThemeInterface;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\DebugBar;

use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\Note;
use Fisharebest\Webtrees\Source;
use Fisharebest\Webtrees\Submitter;
use Fisharebest\Webtrees\Repository;
use Illuminate\Support\Collection;

/** @var string $subject */
/** @var Collection $items */
?>

<html>
    <head>
        <title><?= $subject ?></title>
        <?php foreach (app(ModuleThemeInterface::class)->stylesheets() as $stylesheet) : ?>
            <link rel="stylesheet" href="<?= e($stylesheet) ?>">
        <?php endforeach ?>
        <?= View::stack('styles') ?>
        <?= app(ModuleService::class)->findByInterface(ModuleGlobalInterface::class)->map(static function (ModuleGlobalInterface $module): string {
    return $module->headContent();
        })->implode('') ?>

        <?= DebugBar::renderHead() ?>
    </head>
    <body>

        <?php foreach ($items as $tree => $changes) : ?>
            <h3><?= $tree ?></h3>
            <br/>
            <?php foreach ($changes as $change) : ?>
                <?php $record = $change->record; ?>
        
                <span>
                    <?php $tag = $record["tag"]; ?>
                    <?php if ($tag === Individual::RECORD_TYPE) : ?>
                        <?= view('icons/individual') ?>
                        <span class="sr-only"><?= I18N::translate('Individual') ?></span>
                    <?php elseif ($tag === Family::RECORD_TYPE) : ?>
                        <?= view('icons/family') ?>
                        <span class="sr-only"><?= I18N::translate('Family') ?></span>
                    <?php elseif ($tag === Media::RECORD_TYPE) : ?>
                        <?= view('icons/media') ?>
                        <span class="sr-only"><?= I18N::translate('Media') ?></span>
                    <?php elseif ($tag === Note::RECORD_TYPE) : ?>
                        <?= view('icons/note') ?>
                        <span class="sr-only"><?= I18N::translate('Note') ?></span>
                    <?php elseif ($tag === Source::RECORD_TYPE) : ?>
                        <?= view('icons/source') ?>
                        <span class="sr-only"><?= I18N::translate('Source') ?></span>
                    <?php elseif ($tag === Submitter::RECORD_TYPE) : ?>
                        <?= view('icons/submitter') ?>
                        <span class="sr-only"><?= I18N::translate('Submitter') ?></span>
                    <?php elseif ($tag === Repository::RECORD_TYPE) : ?>
                        <?= view('icons/repository') ?>
                        <span class="sr-only"><?= I18N::translate('Repository') ?></span>
                    <?php endif ?>
                </span>

                <a href="<?= e($record["url"]) ?>"><?= $record["fullName"] ?></a>

                (<?= $change->time->format('Y-m-d'); ?>)
                <br/>
            <?php endforeach ?>
        <?php endforeach ?>
        <script src="<?= e(asset('js/vendor.min.js')) ?>"></script>
        <script src="<?= e(asset('js/webtrees.min.js')) ?>"></script>
    </body>
</html>
