<?php

use EvanG\Modules\MailSystem\MailSystem;
use EvanG\Modules\MailSystem\Settings;
use Fisharebest\Localization\Locale\LocaleInterface;
use Fisharebest\Localization\Translator;

use Fisharebest\Webtrees\Date\GregorianDate;
use Fisharebest\Webtrees\Gedcom;
use Fisharebest\Webtrees\Module\ModuleThemeInterface;

use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\Note;
use Fisharebest\Webtrees\Source;
use Fisharebest\Webtrees\Submitter;
use Fisharebest\Webtrees\Repository;
use Illuminate\Support\Collection;

/** @var Settings $args */
/** @var string $subject */
/** @var Collection $items */
/** @var MailSystem $module */
/** @var Translator $translator */
/** @var LocaleInterface $locale */


$getDate = function ($dateString) {
    $date = date_parse($dateString);
    return new GregorianDate(gregoriantojd($date["month"], $date["day"], $date["year"]));
};

$getIcon = function ($name, $height = 16) use ($translator, $module, $args) {
    $format = $args->getImageFormat();
    $url = $module->assetUrl('img/' . $format . '/' . $name . '.' . $format);
    ?>
    <img height="<?= $height ?>" src="<?= $url ?>" alt="<?= $translator->translate($name) ?>"/>
<?php }; ?>

<!DOCTYPE html>
<html lang="<?= $locale->languageTag() ?>">
<head>
    <title><?= $subject ?></title>

    <style>
        body {
            margin: 0;
        }

        main ~ br {
            display: block;
            margin: 1em 0 0 0;
        }

        slot {
            display: block;
            padding: 1em;
        }

        footer {
            padding: 1em;
            background: #cccccc;
        }

        .treeName {
            font-weight: bold;
        }

        .tree div {
            padding-left: 1em;
        }

        .date {
            margin-top: 0.5em;
            margin-bottom: 0.25em;
        }

        .treeChanges .changes {
            padding-bottom: 0.5em;
        }

        .treeChanges .changes .recordTypeIcon {
            display: inline-block;
            text-align: center;
            min-width: 1.5em;
        }

        .treeChanges .changes .recordTypeIcon img {
            height: 1rem;
        }

        .treeChanges .changes .record {
            vertical-align: middle;
        }

        .anniversary {
            clear: both;
            margin-bottom: 0.5em;
        }

        .anniversary .anniversary-picture {
            float: left;
            margin-right: 1em;
            width: 50px;
            height: 50px;
            background-color: lightgray;
            border-radius: 50%;
            overflow: hidden;
        }

        .anniversary .anniversary-picture img {
            max-height: 100%;
            max-width: 100%;
        }
    </style>

    <?php foreach (app(ModuleThemeInterface::class)->stylesheets() as $stylesheet) : ?>
        <link rel="stylesheet" href="<?= e($stylesheet) ?>">
    <?php endforeach ?>
</head>
<body>
<main>
    <?php foreach ($items as $tree => $data) : ?>
        <section id="<?= $tree ?>" class="tree">
            <h3 class="treeName">
                <span style="vertical-align: text-bottom;"><?php $getIcon('tree', 32); ?></span>
                <?= ucwords($tree) ?>
            </h3>
            <?php $changesData = $data["changes"] ?>
            <div class="treeChanges" id="<?= $tree ?>-changes">
                <h4><?php $getIcon('changes', 24) ?> <?= $translator->translate("Changes") ?></h4>
                <div>
                    <?php if ($changesData->isEmpty()) { ?>
                        <p><?= sprintf($translator->translatePlural('There were no changes during the day.', 'There have been no changes within the last %s days.', $args->getDays()), $locale->number($args->getDays())); ?>
                    <?php } else foreach ($changesData as $date => $changes) : ?>
                        <h5 id="<?= $tree ?>-changes-<?= $date ?>" class="date"><?= $getDate($date)->format("%d %F %Y") ?></h5>
                        <div class="changes">
                            <?php foreach ($changes as $change) : ?>
                                <?php $record = $change->record; ?>
                                <div id="<?= $record["xref"] ?>" class="change">
                                <span class="recordTypeIcon">
                                    <?php $tag = $record["tag"]; ?>
                                    <?php
                                    if ($tag === Individual::RECORD_TYPE) $getIcon('individual');
                                    else if ($tag === Family::RECORD_TYPE) $getIcon('family');
                                    else if ($tag === Media::RECORD_TYPE) $getIcon('media');
                                    else if ($tag === Note::RECORD_TYPE) $getIcon('note');
                                    else if ($tag === Source::RECORD_TYPE) $getIcon('source');
                                    else if ($tag === Submitter::RECORD_TYPE) $getIcon('submitter');
                                    else if ($tag === Repository::RECORD_TYPE) $getIcon('repository');
                                    ?>
                                </span>
                                    <a class="record" href="<?= e($record["url"]) ?>"><?= $record["fullName"] ?></a>
                                </div>
                            <?php endforeach ?>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>

            <?php $anniversariesData = $data["anniversaries"] ?>
            <div class="treeAnniversaries" id="<?= $tree ?>-anniversaries">
                <h4><?php $getIcon('anniversaries', 24) ?> <?= $translator->translate("Anniversaries") ?></h4>
                <div>
                    <?php if ($anniversariesData->isEmpty()) { ?>
                        <p><?= sprintf($translator->translatePlural('There were no changes during the day.', 'There have been no changes within the last %s days.', $args->getDays()), $locale->number($args->getDays())); ?>
                    <?php } else foreach ($anniversariesData as $date => $anniversaries) : ?>
                        <h5 id="<?= $tree ?>-anniversaries-<?= $date ?>" class="date"><?= $getDate("0" . $date)->format("%d %F") ?></h5>
                        <div class="anniversaries">
                            <?php foreach ($anniversaries as $anniversary) : ?>
                                <div id="<?= $anniversary["xref"] ?>-<?= $anniversary["id"] ?>" class="anniversary">
                                    <span class="anniversary-picture">
                                    <?php if (!empty($anniversary["picture"])) : ?>
                                        <img src="<?= $anniversary["picture"] ?>" height="50" alt=""/>
                                    <?php endif ?>
                                    </span>
                                    <span class="anniversary-info">
                                        <span><?php
                                            $tag = $anniversary["tag"];
                                            $age = $anniversary["age"];
                                            $name = '<a class="record" href="' . e($anniversary["url"]) . '">' . $anniversary["name"] . '</a>';
                                            if (in_array($tag, Gedcom::BIRTH_EVENTS)) echo sprintf($translator->translate('Birth of %1$s (%2$s years ago)'), $name, $age);
                                            else if (in_array($tag, Gedcom::MARRIAGE_EVENTS)) echo sprintf($translator->translate('Marriage of %1$s (%2$s years ago)'), $name, $age);
                                            else if (in_array($tag, Gedcom::DEATH_EVENTS)) echo sprintf($translator->translate('Death of %1$s (%2$s years ago)'), $name, $age);
                                            ?></span>
                                        <br/>
                                        <span class="anniversary-date"><?= $getDate($anniversary["date"])->format("%d %F %Y") ?></span>
                                    </span>
                                </div>
                            <?php endforeach ?>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        </section>
    <?php endforeach ?>
</main>
<br/>
<footer>
    <small>
        <?= sprintf($translator->translate("This email was autogenerated by Webtrees and programmed with ❤ by %s"),
            "<a href=\"https://github.com/06Games/Webtrees-MailSystem\">Evan Galli</a>") ?>
    </small>
</footer>
</body>
</html>
