name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install dependencies
        run: sudo apt install -y gettext

      - name: Build module
        run: composer archive -f zip --file evang-mailsystem-$(cat version.txt)

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: evang-mailsystem-${{cat version.txt}}
          path: evang-mailsystem-${{cat version.txt}}.zip
          if-no-files-found: error
