name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install dependencies
        run: sudo apt install -y gettext

      - name: Set output filename
        run: |
          echo "outputName=evang-mailsystem-$(cat version.txt)" >> $GITHUB_ENV

      - name: Build module
        run: composer archive -f zip --file ${{ env.outputName }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ env.outputName }}
          path: ${{ env.outputName }}.zip
          if-no-files-found: error

      - name: Adding step summary
        run: |
          url=https://nightly.link/06Games/Webtrees-MailSystem/actions/runs/${{ github.run_id }}/${{ env.outputName }}.zip
          echo 'This artifact is available at [$url]($url)' >> $GITHUB_STEP_SUMMARY

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.outputName }}.zip
          draft: true
